backend:
  name: git-gateway
  branch: main
  auth_scope: "repo"

media_folder: "images/uploads" # Menü resimlerini buraya ekleyebilirsin
public_folder: "/images/uploads"

collections:
  - name: "menu"
    label: "Menu"
    folder: "data" # Menü verilerini JSON/YAML olarak saklayacağımız klasör
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Yemek Adı", name: "name", widget: "string" }
      - { label: "Açıklama", name: "description", widget: "string" }
      - { label: "Fiyat", name: "price", widget: "number" }
      - {
          label: "Kategori",
          name: "category",
          widget: "select",
          options: ["Main Dishes", "Snacks", "Drinks"],
        }
      - { label: "Resim", name: "image", widget: "image" }
